name: hello_doc
description: A new Flutter project.

version: 0.0.0+0
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  material_design_icons_flutter: ^4.0.5555
  back_button_interceptor: ^4.3.0
  uuid: ^2.2.2
  equatable: ^1.2.4
  google_fonts: ^1.1.0

dev_dependencies:
  gate: 
    path: ./packages/gate/

flutter:
 uses-material-design: true
 fonts:
    - family: Ubuntu
      fonts:
      - asset: assets/fonts/Ubuntu-Bold.ttf
        weight: 700
      - asset: assets/fonts/Ubuntu-Medium.ttf
        weight: 500
      - asset: assets/fonts/Ubuntu-Regular.ttf
        weight: 400
      - asset: assets/fonts/Ubuntu-Light.ttf
        weight: 300
